### ISSUE TITLE
[14.0] DOCUMENT LAYOUT : Customize HEADER & FOOTER - Which is the best way to create a new report ?

### ISSUE THREAD

**Issue by yboujraf** [younismahsud/odoodiscussions#1]
Dear @younismahsud 

Thanks for the video on youtube [customize Header/footer](https://www.youtube.com/watch?v=wrJ4DH9HSlc) and your repository.

I am a newbie and I'd like to create some reports for my accountant.

Myself, I prefer to create a new module with my report to be sure if any update of Odoo I will not lose the report.

Is it the way in your repository how to do it? and which IDE (editor) are you using?

Finally, I have some documents, are you able to provide some services for that?

Best Regards,

**Comment by younismahsud** [comment]
@yboujraf thanks for your appreciation and your comment.

If you want to learn Odoo from scratch then you can join our technical course: [Odoo technical course](https://www.youtube.com/playlist?list=PLT3v18VYaHYV5u23IMGVZdXQ4s7aLGCPD). In this course, I have explained from scratch that how you can create a custom module and how to set up Odoo for development purposes with PyCharm (Code editor).

During this course, if you face any issue or want to ask any question then join our discord server: [Odoo discussions](https://discord.gg/GspyA68).

If you want to contact us for services then please drop an email at m.younis.mahsud@gmail.com

Thank you.
